# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PA8' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PA8
    pod 'MBProgressHUD'
    
  #target 'PA8Tests' do
    #inherit! :search_paths
    # Pods for testing
  #end

  #target 'PA8UITests' do
    # Pods for testing
  #end

end
